export const SECTOR_STOCKS = {
  healthcare: [
    { symbol: 'JNJ', name: 'Johnson & Johnson', marketCap: '450B' },
    { symbol: 'PFE', name: 'Pfizer', marketCap: '280B' },
    { symbol: 'UNH', name: 'UnitedHealth Group', marketCap: '520B' },
    { symbol: 'ABBV', name: 'AbbVie', marketCap: '310B' },
    { symbol: 'MRK', name: 'Merck', marketCap: '290B' },
    {
      symbol: 'TMO',
      name: 'Thermo Fisher Scientific',
      marketCap: '210B',
    },
    { symbol: 'ABT', name: 'Abbott Laboratories', marketCap: '190B' },
    { symbol: 'LLY', name: 'Eli Lilly', marketCap: '850B' },
    { symbol: 'MDT', name: 'Medtronic', marketCap: '110B' },
    {
      symbol: 'BMY',
      name: 'Bristol Myers Squibb',
      marketCap: '120B',
    },
  ],
  technology: [
    { symbol: 'AAPL', name: 'Apple Inc.', marketCap: '3.4T' },
    {
      symbol: 'MSFT',
      name: 'Microsoft Corporation',
      marketCap: '2.8T',
    },
    { symbol: 'GOOGL', name: 'Alphabet Inc.', marketCap: '1.7T' },
    { symbol: 'AMZN', name: 'Amazon.com Inc.', marketCap: '1.5T' },
    {
      symbol: 'META',
      name: 'Meta Platforms Inc.',
      marketCap: '800B',
    },
    { symbol: 'TSLA', name: 'Tesla Inc.', marketCap: '750B' },
    { symbol: 'NVDA', name: 'NVIDIA Corporation', marketCap: '1.1T' },
    { symbol: 'NFLX', name: 'Netflix Inc.', marketCap: '200B' },
    { symbol: 'CRM', name: 'Salesforce Inc.', marketCap: '250B' },
    { symbol: 'ORCL', name: 'Oracle Corporation', marketCap: '340B' },
  ],
  finance: [
    {
      symbol: 'JPM',
      name: 'JPMorgan Chase & Co.',
      marketCap: '580B',
    },
    {
      symbol: 'BAC',
      name: 'Bank of America Corp.',
      marketCap: '320B',
    },
    {
      symbol: 'WFC',
      name: 'Wells Fargo & Company',
      marketCap: '200B',
    },
    {
      symbol: 'GS',
      name: 'Goldman Sachs Group Inc.',
      marketCap: '140B',
    },
    { symbol: 'MS', name: 'Morgan Stanley', marketCap: '180B' },
    { symbol: 'C', name: 'Citigroup Inc.', marketCap: '120B' },
    {
      symbol: 'AXP',
      name: 'American Express Company',
      marketCap: '190B',
    },
    { symbol: 'BLK', name: 'BlackRock Inc.', marketCap: '130B' },
    { symbol: 'SPGI', name: 'S&P Global Inc.', marketCap: '150B' },
    { symbol: 'USB', name: 'U.S. Bancorp', marketCap: '70B' },
  ],
  energy: [
    {
      symbol: 'XOM',
      name: 'Exxon Mobil Corporation',
      marketCap: '450B',
    },
    { symbol: 'CVX', name: 'Chevron Corporation', marketCap: '280B' },
    { symbol: 'COP', name: 'ConocoPhillips', marketCap: '150B' },
    { symbol: 'EOG', name: 'EOG Resources Inc.', marketCap: '70B' },
    { symbol: 'SLB', name: 'Schlumberger Limited', marketCap: '65B' },
    {
      symbol: 'PXD',
      name: 'Pioneer Natural Resources',
      marketCap: '60B',
    },
    { symbol: 'KMI', name: 'Kinder Morgan Inc.', marketCap: '40B' },
    { symbol: 'OXY', name: 'Occidental Petroleum', marketCap: '55B' },
  ],
  retail: [
    { symbol: 'WMT', name: 'Walmart Inc.', marketCap: '650B' },
    { symbol: 'HD', name: 'The Home Depot Inc.', marketCap: '400B' },
    {
      symbol: 'COST',
      name: 'Costco Wholesale Corporation',
      marketCap: '380B',
    },
    { symbol: 'TGT', name: 'Target Corporation', marketCap: '70B' },
    {
      symbol: 'LOW',
      name: "Lowe's Companies Inc.",
      marketCap: '140B',
    },
    { symbol: 'TJX', name: 'TJX Companies Inc.', marketCap: '140B' },
    {
      symbol: 'SBUX',
      name: 'Starbucks Corporation',
      marketCap: '110B',
    },
    { symbol: 'NKE', name: 'NIKE Inc.', marketCap: '200B' },
  ],
};